export declare class VisitFilter {
    studyUid?: string;
    siteUid?: string;
    /**
     * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
     */
    subjectIdentifier?: string;
    visitProcedureName?: string;
    /**
     * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitExecutionTitle: string;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState?: number;
    minScheduledDateUtc?: Date;
    maxScheduledDateUtc?: Date;
    minExecutionDateUtc?: Date;
    maxExecutionDateUtc?: Date;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
}
export declare class VisitMetaRecord {
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    visitUid: string;
    studyUid: string;
    siteUid: string;
    /**
     * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
     */
    subjectIdentifier: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
export declare class DataRecordingMetaRecord {
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    dataRecordingUid: string;
    visitUid: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
export declare class CustomFieldDescriptor {
    technicalName: string;
    isRequired: boolean;
    displayLabel: string;
    inputDescription?: string;
    defaultValue?: string;
    presets?: string[];
    presetsOnly?: boolean;
    regularExpression?: string;
}
export declare class VisitFields extends VisitMetaRecord {
    /**
     * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitProcedureName: string;
    /**
     * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitExecutionTitle: string;
    /**
     * the estimated date when the visit is scheduled for execution *this field is optional
     */
    scheduledDateUtc?: Date;
    /**
     * the real date, when the visits was executed *this field is optional
     */
    executionDateUtc?: Date;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState: number;
    /**
     * *this field is optional (use null as value)
     */
    executingPerson?: string;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    visitUid: string;
    studyUid: string;
    siteUid: string;
    /**
     * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
     */
    subjectIdentifier: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
/**
 * A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
 */
export declare class VisitFhirRessourceContainer extends VisitMetaRecord {
    /**
     * a HL7 ['Appointment'](http://www.hl7.org/fhir/appointment.html) resource in json format
     */
    appointmentRessource?: Object;
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    visitUid: string;
    studyUid: string;
    siteUid: string;
    /**
     * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
     */
    subjectIdentifier: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
export declare class BatchableVisitMutation {
    /**
     * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitProcedureName?: string;
    /**
     * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitExecutionTitle?: string;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState?: number;
    /**
     * *this field is optional (use null as value)
     */
    executingPerson?: string;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
}
export declare class DataRecordingFields extends DataRecordingMetaRecord {
    /**
     * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    dataRecordingName: string;
    /**
     * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    taskExecutionTitle: string;
    /**
     * the estimated date when the visit is scheduled *this field is optional
     */
    scheduledDateTimeUtc?: Date;
    /**
     * the real time, when the data was recorded *this field is optional
     */
    executionDateTimeUtc?: Date;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState: number;
    /**
     * schema-url of the data which were stored inside of the 'RecordedData' field
     */
    dataSchemaUrl: string;
    /**
     * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
     */
    notesRegardingOutcome?: string;
    /**
     * *this field is optional (use null as value)
     */
    executingPerson?: string;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    dataRecordingUid: string;
    visitUid: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
export declare class VisitMutation extends BatchableVisitMutation {
    /**
     * the estimated date when the visit is scheduled for execution *this field is optional
     */
    scheduledDateUtc?: Date;
    /**
     * the real date, when the visits was executed *this field is optional
     */
    executionDateUtc?: Date;
    /**
     * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitProcedureName?: string;
    /**
     * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitExecutionTitle?: string;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState?: number;
    /**
     * *this field is optional (use null as value)
     */
    executingPerson?: string;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
}
export declare class DataRecordingStructure extends DataRecordingFields {
    /**
     * RAW data, in the schema as defined at the 'DataSchemaUrl'
     */
    recordedData: string;
    /**
     * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    dataRecordingName: string;
    /**
     * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    taskExecutionTitle: string;
    /**
     * the estimated date when the visit is scheduled *this field is optional
     */
    scheduledDateTimeUtc?: Date;
    /**
     * the real time, when the data was recorded *this field is optional
     */
    executionDateTimeUtc?: Date;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState: number;
    /**
     * schema-url of the data which were stored inside of the 'RecordedData' field
     */
    dataSchemaUrl: string;
    /**
     * additional notes regarding this dedcated execution (supplied by the execution person) *this field is optional (use null as value)
     */
    notesRegardingOutcome?: string;
    /**
     * *this field is optional (use null as value)
     */
    executingPerson?: string;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    dataRecordingUid: string;
    visitUid: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
export declare class VisitStructure extends VisitFields {
    dataRecordings?: DataRecordingStructure[];
    /**
     * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitProcedureName: string;
    /**
     * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
     */
    visitExecutionTitle: string;
    /**
     * the estimated date when the visit is scheduled for execution *this field is optional
     */
    scheduledDateUtc?: Date;
    /**
     * the real date, when the visits was executed *this field is optional
     */
    executionDateUtc?: Date;
    /**
     * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
     */
    executionState: number;
    /**
     * *this field is optional (use null as value)
     */
    executingPerson?: string;
    /**
     * Custom fields as defined by the Service. Call 'GetCustomFieldDescriptors' to get information about supported/required fields. Any passed values for undefined fields will be ignored.
     */
    customFields?: Object;
    /**
     * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
     */
    visitUid: string;
    studyUid: string;
    siteUid: string;
    /**
     * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
     */
    subjectIdentifier: string;
    /**
     * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
     */
    isArchived: boolean;
    /**
     * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
     */
    modificationTimestampUtc: number;
}
//# sourceMappingURL=models.d.ts.map