"use strict";
/* based on ORSCF VisitData Contract v1.7.0.0 */
var __extends = (this && this.__extends) || (function () {
    var extendStatics = function (d, b) {
        extendStatics = Object.setPrototypeOf ||
            ({ __proto__: [] } instanceof Array && function (d, b) { d.__proto__ = b; }) ||
            function (d, b) { for (var p in b) if (Object.prototype.hasOwnProperty.call(b, p)) d[p] = b[p]; };
        return extendStatics(d, b);
    };
    return function (d, b) {
        extendStatics(d, b);
        function __() { this.constructor = d; }
        d.prototype = b === null ? Object.create(b) : (__.prototype = b.prototype, new __());
    };
})();
Object.defineProperty(exports, "__esModule", { value: true });
exports.VisitStructure = exports.DataRecordingStructure = exports.VisitMutation = exports.DataRecordingFields = exports.BatchableVisitMutation = exports.VisitFhirRessourceContainer = exports.VisitFields = exports.CustomFieldDescriptor = exports.DataRecordingMetaRecord = exports.VisitMetaRecord = exports.VisitFilter = void 0;
var VisitFilter = /** @class */ (function () {
    function VisitFilter() {
        /**
         * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        this.visitExecutionTitle = '';
    }
    return VisitFilter;
}());
exports.VisitFilter = VisitFilter;
var VisitMetaRecord = /** @class */ (function () {
    function VisitMetaRecord() {
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        this.visitUid = '';
        this.studyUid = '';
        this.siteUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        this.subjectIdentifier = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        this.modificationTimestampUtc = 0;
    }
    return VisitMetaRecord;
}());
exports.VisitMetaRecord = VisitMetaRecord;
var DataRecordingMetaRecord = /** @class */ (function () {
    function DataRecordingMetaRecord() {
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        this.dataRecordingUid = '';
        this.visitUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        this.modificationTimestampUtc = 0;
    }
    return DataRecordingMetaRecord;
}());
exports.DataRecordingMetaRecord = DataRecordingMetaRecord;
var CustomFieldDescriptor = /** @class */ (function () {
    function CustomFieldDescriptor() {
        this.technicalName = '';
        this.isRequired = false;
        this.displayLabel = '';
    }
    return CustomFieldDescriptor;
}());
exports.CustomFieldDescriptor = CustomFieldDescriptor;
var VisitFields = /** @class */ (function (_super) {
    __extends(VisitFields, _super);
    function VisitFields() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        /**
         * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.visitProcedureName = '';
        /**
         * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.visitExecutionTitle = '';
        /**
         * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
         */
        _this.executionState = 0;
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.visitUid = '';
        _this.studyUid = '';
        _this.siteUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        _this.subjectIdentifier = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return VisitFields;
}(VisitMetaRecord));
exports.VisitFields = VisitFields;
/**
 * A structure containing HL7/FHIR-Ressources (JSON only) and the essential fields which are required to qualify a ORSCF record.
 */
var VisitFhirRessourceContainer = /** @class */ (function (_super) {
    __extends(VisitFhirRessourceContainer, _super);
    function VisitFhirRessourceContainer() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.visitUid = '';
        _this.studyUid = '';
        _this.siteUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        _this.subjectIdentifier = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return VisitFhirRessourceContainer;
}(VisitMetaRecord));
exports.VisitFhirRessourceContainer = VisitFhirRessourceContainer;
var BatchableVisitMutation = /** @class */ (function () {
    function BatchableVisitMutation() {
    }
    return BatchableVisitMutation;
}());
exports.BatchableVisitMutation = BatchableVisitMutation;
var DataRecordingFields = /** @class */ (function (_super) {
    __extends(DataRecordingFields, _super);
    function DataRecordingFields() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        /**
         * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.dataRecordingName = '';
        /**
         * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.taskExecutionTitle = '';
        /**
         * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
         */
        _this.executionState = 0;
        /**
         * schema-url of the data which were stored inside of the 'RecordedData' field
         */
        _this.dataSchemaUrl = '';
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.dataRecordingUid = '';
        _this.visitUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return DataRecordingFields;
}(DataRecordingMetaRecord));
exports.DataRecordingFields = DataRecordingFields;
var VisitMutation = /** @class */ (function (_super) {
    __extends(VisitMutation, _super);
    function VisitMutation() {
        return _super !== null && _super.apply(this, arguments) || this;
    }
    return VisitMutation;
}(BatchableVisitMutation));
exports.VisitMutation = VisitMutation;
var DataRecordingStructure = /** @class */ (function (_super) {
    __extends(DataRecordingStructure, _super);
    function DataRecordingStructure() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        /**
         * RAW data, in the schema as defined at the 'DataSchemaUrl'
         */
        _this.recordedData = '';
        /**
         * unique invariant name of ths task-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.dataRecordingName = '';
        /**
         * title of the task execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.taskExecutionTitle = '';
        /**
         * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
         */
        _this.executionState = 0;
        /**
         * schema-url of the data which were stored inside of the 'RecordedData' field
         */
        _this.dataSchemaUrl = '';
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.dataRecordingUid = '';
        _this.visitUid = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return DataRecordingStructure;
}(DataRecordingFields));
exports.DataRecordingStructure = DataRecordingStructure;
var VisitStructure = /** @class */ (function (_super) {
    __extends(VisitStructure, _super);
    function VisitStructure() {
        var _this = _super !== null && _super.apply(this, arguments) || this;
        /**
         * unique invariant name of the visit-procedure as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.visitProcedureName = '';
        /**
         * unique title of the visit execution as defined in the 'StudyWorkflowDefinition' (originated from the sponsor)
         */
        _this.visitExecutionTitle = '';
        /**
         * 0=Unscheduled / 1=Sheduled / 2=Executed / 3=AbortDuringExecution / 4=Skipped / 5=Removed
         */
        _this.executionState = 0;
        /**
         * An [Universally Unique Identifier](https://de.wikipedia.org/wiki/Universally_Unique_Identifier) which can be generated by any origin system and is used to address this ORSCF conform data record in decentralized environments. Note that this Identity must not be changed any more!
         */
        _this.visitUid = '';
        _this.studyUid = '';
        _this.siteUid = '';
        /**
         * identity of the patient which is usually a pseudonym from a corr. 'IdentiyManagementSystem' (the exact semantic is defined per study) *this field has a max length of 100
         */
        _this.subjectIdentifier = '';
        /**
         * This is an internal managed field, which is related to the state of records dedicated to the database. It will be automatically set when a record is archived. A mapping during data import requires opt-in.
         */
        _this.isArchived = false;
        /**
         * This is an internal managed field (UNIX-Timestamp), which is related to the state of records dedicated to the database. It will be automatically set to the current time when a record is created, updated, archived or unarchived, but cannot be updated from outside and must not be mapped during data imports.
         */
        _this.modificationTimestampUtc = 0;
        return _this;
    }
    return VisitStructure;
}(VisitFields));
exports.VisitStructure = VisitStructure;
//# sourceMappingURL=models.js.map